xhprof.lo: /usr/local/etc/xhprof/extension/xhprof.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/local/etc/xhprof/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/local/etc/xhprof/extension/xhprof.c -o xhprof.lo 
$(phplibdir)/xhprof.la: ./xhprof.la
	$(LIBTOOL) --mode=install cp ./xhprof.la $(phplibdir)

./xhprof.la: $(shared_objects_xhprof) $(XHPROF_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_xhprof) $(XHPROF_SHARED_LIBADD)

